### ISSUE TITLE
add option to deactivate TLS

### ISSUE THREAD

**Issue by newsgrep** [scubajeff/lespas#10]
I use 1.4.5 of your app and NextCloud 20.0.7

Please add an option to: 
* deactivate TLS and / or 
* to allow self signed certificates without having to import them into Android. 

It would make testing of the app and also using it at home e.g. in my own WiFi much more easy. 

https://github.com/scubajeff/lespas/issues/8#issuecomment-772540591 
did not work for me, or i was not able to make it work. 

btw: 
were do I find your donation link. 
And also thank you for your work and for publishing the recent changes in the F-Droid description.

**Comment by scubajeff** [comment]
Do you mean that Les Pas won't work with a imported self-signed certificate in your phone (that would be a bug in Les Pas), or you have difficulties importing certs and simply want a version which works in that particular case (that would make it a new feature)?

**Comment by newsgrep** [comment]
I mean that I was not able to import the self-signed public certificate into Android 9 (rooted) and Android 8 (not rooted). I guess I did something wrong. So this is a request for a new feature. 

So I guess I have difficulties importing certs and simply want a version which simply ask if I would like to trust the "untrusted" self signed cert that is offerd by the server. And also add a checkbox to deactivate TLS completely. For teasting or use in a trusted local network. So that would make it a new feature. 

btw:
One of the links to the cert import guides is broken.

Thank you a lot for your time.

**Comment by scubajeff** [comment]
I see. Trusting a untrusted self-signed cert is a trivial job, lots of guide on the net, these apps do have a place in testing environment, but not for production. That's why Google won't allow these kind of apps listing on Google Play (yes, they do review your code), I'm not sure about F-Droid's policy, but anyway, bad practice.

Btw, I just try visiting the two links in the FAQ. Both works.

**Comment by BristolPiggy** [comment]
Im guessing this is the correct thread but please forgive me if I am wrong. I have set up my own Nextcloud appliance and access my drive through a zerotier private network, which runs on a http network not https. Due to this the app will not work at all and there is no option to over-ride the https encryption.

I accept google may have their rules as to levels of encryption however I have come to this via F-droid, which I thought allowed people to choose rather than be dictated to. 

Using Zerotier's encypted private network is free and allows people to access their own self hosted cloud appliances, but at the cost of not being able to use yours and similar applications. 

Is it definately not possible to let people choose the level of risk they undertake?

**Comment by scubajeff** [comment]
Sorry that Les Pas doesn't work for you. I did a little reading on Zerotier, it seems like a VPN or SDN overlay network, that won't stop anyone from running https on top of it.

**Comment by ishent** [comment]
I'd like to use your app but unfortunately I am still not able to make Android to trust my self-signed certificate. newsgrep's suggestion would help me and surely other people too.

I don't understand what you mean with "Google won't allow these kind of apps listing on Google" as there are apps that allow to sync with NextCloud through HTTP and/or have a setting to ignore TLS certificate errors like Joplin (https://play.google.com/store/apps/details?id=net.cozic.joplin) or NextCloud Client app (https://play.google.com/store/apps/details?id=com.nextcloud.client).

I would appreciate you reconsider including this feature as you wrote it's trivial but I would also understand if you don't.

Thank you for your time and for an app I am sure it's great.
