### ISSUE TITLE
Add "sync now" button

### ISSUE THREAD

**Issue by BettaGeorge** [scubajeff/lespas#12]
**Is your feature request related to a problem? Please describe.**
It's frustrating when you want to organize some little thing real quick, and then have to wait until auto-sync fetches the images from your server. Sometimes I want to force my images to be synced _right now_, not sometime in the next six hours.

**Describe the solution you'd like**
A simple button that forces immediate synchronisation would be great. Doesn't matter where it is, it can even be in the settings menu. I just want to be able to use it every now and then.

**Comment by scubajeff** [comment]
The easy way to do this, if not the obvious way, is to select the photo and share it to Les Pas again, then you can choose another album to host it.

**Comment by scubajeff** [comment]
Each time you open Les Pas app, it actually sync with server once.

**Comment by BettaGeorge** [comment]
Ah, I was not aware of that, thank you.

I would argue that the feature request is still valid though, because it is not intuitively clear that the workaround "close the app and reopen it" works.

**Comment by scubajeff** [comment]
Thank you. My intention is to make the sync process as robust as possible so that users will actually forget it at all. It's a feeling of it just works, don't worry too much about it. 

Actually, if you make any changes in the app, it will sync immediately with server. The only major shortcoming now is I don't have adequate skills to implement sync function on server side. If you make any changes on server, you will have to wait at most 6 hours to see those changes on your phone. That's all the periodic sync function is all about. 

After I finish the facial recognition part, this is one of the major features to implement besides sharing albums among nextcloud users.

**Comment by jkufner** [comment]
Also, it would be very nice to have an indicator, that the sync is running, so that the user can see when everything is up-to-date. This is extremely useful when backing up the phone on some restaurant wifi in middle of nowhere. In such situations, a simple progressbar is just amazing (while in daily life with a good connection nobody cares).

**Comment by steviehs** [comment]
I hope, I do not hjijack this ticket: I tried  the "sync camera roll" feature but with limited success: it seems, I even have to restart lespas, so that the pictures get uploaded... not even a 6 hours wait helps...

I would love to use this feature instead of the quite unreliable nextcloud upload sync...

**Comment by scubajeff** [comment]
release 2.5.20 has a re-sync button
