### ISSUE TITLE
Different picture folders visbile in app (not only camera roll)

### ISSUE THREAD

**Issue by flutschepfeil** [scubajeff/lespas#122]
Lespas offers a nice way of organizing/selecting and backup your photos.
The current problem for me is that I can only choose photos from camera roll, but not photos which were send via another app or image I saved. The reason seems to be that those pictures are in a different folder than camera roll.

In the app itself only camera roll seems easily visible, other folders not.

It would be nice if it was possible to have all folders that include pictures/videos at the homescreen of the app. Then it can be used as gallery and also backup app.
Introducing 2 apps is always difficult to explain to the wife and adds a complexity factor ;)

**Comment by scubajeff** [comment]
Les Pas started as a mobile display and a sharing vehicle for my own photographic works, I didn't pay much attention to management of phone's images, since I'm not a fan of mobile photography and don't like the idea of rebuilding the wheel of a file manager. However I start to realize that it would be better if Les Pas acts more like a general purpose picture manager. I will put this in my todo list. But it won't happen soon.

**Comment by frederikb96** [comment]
My current work around is folder sync Pro. Here I set up a local to local folder synchronization and then I use the "move instead of copy" function to move all pictures from the source folder to the camera roll folder. Thus, I basically misuse this app to simply move all pictures from other folders to the camera roll folder. My family members are quite happy with this functionality. 
Consequently,  there workflow is to simply sort all photos from the camera roll album to the new desired albums via Les Pas since all photos on the phone are always in the camera roll folder. 

The folder sync app works in the background. You can also enable instant sync to immediately move files to the camera roll folder. So no interaction from the user required here. 

But I would also appreciate the requested feature ones there is time to implement it :)

**Comment by scubajeff** [comment]
A revamp of device media managment is brewing in the lab, will replace the current half-heartedly camera roll feature. It will be more Google Photo feel plus folder sync type of backup setting for each folder you chose. Still need another week or two.
