### ISSUE TITLE
Select local folders on Android

### ISSUE THREAD

**Issue by lgwapnitsky** [scubajeff/lespas#14]
I'd like the ability to select which folders are synced via the camera roll function, rather than all downloaded images being uploaded

**Comment by scubajeff** [comment]
Les Pas follows android's privacy guideline and use android's SAF (storage access framework) to read from your phone's camera roll, to be specific, the content of phone's DCIM folder. It's up to Android OS to determine what files fall in that category. As Google just announced several days ago, it will enforce Android 11's scope storage feature from this August. Scope storage is all about protecting user's privacy, it restrict apps from accessing storage area which are not created by their own. Apps without special permission granted can only read from DCIM and Pictures folder using SAF.

**Comment by BettaGeorge** [comment]
I think @lgwapnitsky was talking about the opposite problem – they do not want the option to sync _more_ folders, they want the option to sync _fewer_ folders. As in, currently you have two options:

- sync nothing from camera roll
- sync everything in your Pictures folder and everything in your DCIM folder

If I understand correctly, @lgwapnitsky would like the following option (for example):

- sync everything from your DCIM folder, but from your Pictures folder, sync only `Pictures/Work`, but not `Pictures/MyPhonePorn`

I would probably not use that because I organize everything in albums, but I think that is what they meant.

**Comment by scubajeff** [comment]
Les Pas only works on DCIM folder, not Picture folder.

**Comment by manny8975** [comment]
Hi, love this app been searching for a third party photo library for nextcloud for the past week and missed this one somehow.

I'm not sure @BettaGeorge is correct, I think @lgwapnitsky and I want the same functionality. I'd like to be able to sync folders other than just what is in DCMI. I know @scubajeff mentioned this is due to new android limitations on what files an aop can access and also mentioned its not possible without special permissions. 
Could these special permissions be an optional extra to enable in settings so that Les Pas can use all the media from the android phone (similar to VLC, for example?).

Without this, only my camera roll is backed up and no downloaded photos are backed up (amount other things). I also wanted to ask if the camera roll view could be modified to include the photos from any remote albums too, acting as an "All photos" viewing option similar to default views in iOS/Google Photos.

Thanks

**Comment by scubajeff** [comment]
@manny8975 The additional permission idea looks feasible.

**Comment by manny8975** [comment]
@scubajeff Yes bit of a headache to setup to be honest, not too bad once that was done though. I'm essentially just trying to replace Google photos and the stock nextcloud photo/video experience is not the best. My current setup is a nice compromise.

Any thoughts on an option for showing all albums in the camera roll/adding another album that includes all photos?

**Comment by scubajeff** [comment]
@manny8975 Do you mean all the media files in your phone? or all the media files on your NC server home? or both?

**Comment by manny8975** [comment]
@scubajeff Both ideally, but all media files in NC would do the job.

**Comment by scubajeff** [comment]
@manny8975 That's nearly impossible. Nextcloud API is base on WebDAV, to get all files meta by reading directory tree recusively just take forever to finish.

**Comment by manny8975** [comment]
@scubajeff Not sure on the workings of the API myself, you know more than me. That being said, how does the official nextcloud app achieve this? 

Would the option of selecting a specific photos folder (that may have subfolders) reduce the time to read the directory tree? Maybe a local cache of some sort that indexes the files on NC and then runs through the index on startup to check it is up to date before then checking for new files?

**Comment by scubajeff** [comment]
Both your suggestions are actually implemented in Les Pas right now. Albums synced with lespas/ folder on server works by utilizing NC's fileid and etag meta data. This works quite well since it is the same mechanism NC used for it's own clients. But seems like a overkill to me to use it with a casual backup use case. That's why camera roll archive management is based on WebDAV PROPFIND read on server's DCIM/ folder with indefinite folder depth.

**Comment by manny8975** [comment]
@scubajeff Yeah you're right. Not sure why I was clarifying those points to be honest, since that functionality is already there.
What I want is to be able to see a full list of all photos, similar to the camera roll but it uses /DCMI and /lespas instead of just /DCMI as it is currently.

I tested with my setup by changing nextcloud to upload local media to the NC DCMI directory. This shows all my media in the camera roll album but does not preserve the albums so I think including an option that allows the NC /lespas folder to be included in the camera roll album would allow me to maintain my albums in lespas and also have a view that shows me all photos.

**Comment by scubajeff** [comment]
I still can't understand your use case, if you want to use the album feature, why not just create your albums in lespas?

**Comment by manny8975** [comment]
My use case is that similar to Google photos. I simply want to be able to see all media (all photos from all albums) in one view, as well as all albums individually. For example:
Albums:
> Holiday
> DCMI
> Download

Functionality: 
> An album for each of these within lespas (already implemented)
> A view that let's me see all photos from all albums i.e. Holiday, DCMI, Download 

From my knowledge the latter is not currently possible.

I have found a similar app [PlayStore/](https://play.google.com/store/apps/details?id=com.nkming.nc_photos&gl=US)[Source](https://gitlab.com/nkming2/nc-photos)  that provides what I am looking for. However, this app does not generate video previews on its own and instead relies on nextcloud to provide them, which my managed provider does not support - plus I prefer the UI of lespas.

**Comment by scubajeff** [comment]
First of all, to avoid confusion, let us agree on that 'album' means album created in Lespas app. 

As you mentioned, you already have some albums in Lespas, and I bet you had also used the camera roll managment feature, been able to see all your camera shots. Now, what you want is for the camera roll manager to manage images in folders other than DCIM, is that right?

**Comment by manny8975** [comment]
Correct, we're on the same page.

**Comment by scubajeff** [comment]
> Les Pas follows android's privacy guideline and use android's SAF (storage access framework) to read from your phone's camera roll, to be specific, the content of phone's DCIM folder. It's up to Android OS to determine what files fall in that category. As Google just announced several days ago, it will enforce Android 11's scope storage feature from this August. Scope storage is all about protecting user's privacy, it restrict apps from accessing storage area which are not created by their own. Apps without special permission granted can only read from DCIM and Pictures folder using SAF.

As I explained early, the only eligible device folder left to be included is 'Pictures', however, I also advocate users not to store any of their files in public folder to avoid being scanned by 3rd party software.

**Comment by frederikb96** [comment]
I am also interested in this topic. To clarify, I would also like to back up with the camera roll function, pictures which are not located within DCIM.

My current solution:
One can use a script or simply the [foldersync](https://foldersync.io/) app to move all pictures automatically from Pictures/Screenshots and Pictures/signal-...pictures... to a folder within DCIM.
Then Les Pas is backing the files up.

About the feature request:
As you said, there is no difference in the DCIM and Pictures folder with regard to privacy. Thus, I would give a thumbs up, to have the option to have checkmarks in the settings, to select the folders from DCIM and Pictures, that you want to have included. Like in the official Nextcloud App.

**Comment by scubajeff** [comment]
I kind of feel the heat myself of the need to backup `screenshot` folder, which is now standardized resting in `Pictures` folder for almost every ROM out there. However, not like `DCIM`, `Pictures` folder is more a wild beast. As Google tighten up it's privacy policy implementation, more and more apps find this folder the last place to dump media files, so I think sub folder exclusion might be a desired feature too. I will see what I can do. It won't happen soon.

**Comment by scubajeff** [comment]
Latest release 2.8.0 added backup of 'Pictures' folder with options to exclude sub folders from backup

**Comment by scubajeff** [comment]
release 2.9.0 brings the new Gallery.
