### ISSUE TITLE
Option to set larger cache

### ISSUE THREAD

**Issue by btittelbach** [scubajeff/lespas#152]
Current Cache size can only be configured to a maximum of 1000Mb.

Les Pas is about 40% with syncing my Albums and the cache is running full. Would be kind of sad to throw away these days of syncing, especially since the phone has enough memory.

**Desired Solution**

Please provide the option to set cache sizes of up to 5Gb.

**Describe alternatives you've considered**
Alternatively, maybe Les Pas should start syncing with the newest albums instead of the oldest and only continue once the cache has been enlarged.

**Comment by scubajeff** [comment]
Cache setting is for remote album's thumbnail and video streaming. If your albums are local album, all photo/video files are save in lespas's private storage in your phone, which won't count against cache.

**Comment by btittelbach** [comment]
Yes. i am syncing my remote album folder collection to my phone. That is exactly the cache for thumbnails that is running out. Thats why I think a max of just 1Gb for remote Thumbnails is quite low.

**Comment by scubajeff** [comment]
This cache setting is for okhttp web cache, your sync won't stop even if it seems to be full.

**Comment by btittelbach** [comment]
Thanks.

What does happen if the cache runs full?
- no more thumbnails of newer albums are downloaded
- thumbnails of older Albums are evicted from the cache during sync
- thumbnails are only downloaded once albums are viewed, only then evicting older thumbnails from the cache 
??

Might still make sense to cache as many thumbnails to the phone as possible, while connected to a wifi in the same network as the server.

**Comment by scubajeff** [comment]
For remote albums, whatever you see on the screen, the cover image in the album list, the thumbnail in the photo list, or the full size photo, and everything in friend's publications too, they all goes in the cache. They are downloaded when the app need them, mostly for viewing purpose. This cache is FIFO, means old one will get evicted when cache is full.

1GB is pretty big for daily usage, because usually you work on just a few recent albums.

When you sync albums for the first time, they will get downloaded for EXIF extracting, those temporary files are stored in the cache too, hence you see the cache got filled up pretty fast if you have a large collection. It's normal, nothing to worry about.

Actually you can always clear this cache from lespas's setting or android system's setting menu to force image refresh.

**Comment by burningT** [comment]
Hi there,
I am interested in this as well as I need my pictures to be available even with the server being out of reach. 

So I am wondering, if all necessary data are locally stored and not part of the limited cache, shouldn't I see pictures I viewed once always after? However, I observe that once I am out of reach of the server, only a subset of images can be viewed. This looks to me as if the cache was indeed limiting.

Extending the cache size would help here to extend usability, I think. So why keep up that limitation?

**Comment by scubajeff** [comment]
There will be a unlimite option for this cache setting in the next release. However, this cache is actually managed by Okhttp library, it's a web cache, means that the miss and reload also has something to do with your web server settings.

**Comment by burningT** [comment]
That sounds great and I would expect it to resolve my issue as well. And yes indeed, in some way my webserver has issues if it is out of reach 😉
