### ISSUE TITLE
Delete locally pictures that are added to a remote album

### ISSUE THREAD

**Issue by vbelloir** [scubajeff/lespas#159]
**Is your feature request related to a problem? Please describe.**
Not really a problem, but a preferred behavior.  
I really don't like when a file is kind of duplicated.
When I create a photo from local Android Gallery in Les Pas, A check box is proposed:
`Album distant, fichiers multimedias stockées uniquement sur le serveur`

in English, I assume it is : `Remote album, multimedia files only stored on server side`.

For me it means that when album is created, photos are copied on the server (indeed they are), and, as they are not needed anymore on the phone, they are removed locally. 

**Describe the solution you'd like**
Photos are removed from phone when they are added to a remote album, and that the checbox is checked.

**Describe alternatives you've considered**
Removing manueally pictures from Les Pas, but is it frindly.

**Additional context**
Where does the name Les Pas come from?

**Comment by scubajeff** [comment]
This feature is already available. In photo import dialog window, there is a 'Move' option at the very top, choosing this function instead of the default 'Copy' function. Mind that, before 'Move' function can be activated, you must have given Les Pas adequate storage access permission.
![Screenshot_20240108_155901](https://github.com/scubajeff/lespas/assets/458032/03509ffa-990a-4135-b852-6b596323b619)

**Comment by vbelloir** [comment]
Damned I missed it. 
I'm so sorry.

Thanks for your job and your app.
