### ISSUE TITLE
Not syncing photos from server

### ISSUE THREAD

**Issue by zoenglinghou** [scubajeff/lespas#2]
**Describe the bug**
After logging in, the app is not syncing photos from NC.

**To Reproduce**
1. Log in and grant access
2. Turn on periodic syncing
3. Wait for a long time (overnight for me)
4. No image/preview showing up

**Expected behavior**
Images/preview showing up in the main interface

**Screenshots**
![Screenshot_20201223-140250](https://user-images.githubusercontent.com/11689106/102998586-59edee00-451f-11eb-9491-e9bd63c20e83.png)
![Screenshot_20201223-140319](https://user-images.githubusercontent.com/11689106/103000159-66277a80-4522-11eb-8fee-16d298a4e2ec.png)

**Smartphone (please complete the following information):**
 - Device: Fairphone 3
 - OS: Android 10
 - Browser: Fennec
 - Version: 83

**Comment by scubajeff** [comment]
app sync with folder /lespas on server. every subfolder under /lespas will appear as an album in app.

**Comment by zoenglinghou** [comment]
Thank you for your answer! I would try it out by simlinking the photos folder to /lespas

**Comment by zoenglinghou** [comment]
hmmm, does the app download from the server? I symlinked my photos and movies photo under `/lespas` and ran `occ file:scan` on them. They show up on the NC web interface but not downloaded on les pas. Les pas can also upload images.
So does symlink not work or does les pas not syncing from server?

**Comment by scubajeff** [comment]
lespas use webdav. i thought webdav can do well with symlink files. will test this on my side today. hang on.

**Comment by scubajeff** [comment]
symlink nextcloud's /Photos folder to /lespas/nextcloud. and a new album 'nextcloud' appeared in my lespas app. could you please give me more detail on how you symlink?

my server setup is nextcloud v20.04 running on ubuntu 20.04

**Comment by zoenglinghou** [comment]
I have the same server setup as yours. I symlinked `/Photos/Camera` and `/Movies/Camera` *with subfolders* to `/lespas/`. I don't know if it is the recursive folder structure that causes les pas to fail.

**Comment by scubajeff** [comment]
recusive is fine although lespas only sync files within those subfolders.

**Comment by PietroMB** [comment]
I have the same issiue described by zoenglinghou, I've also tryed create the directory "/lespas" via browser, but the app looks not upload image at all, but pls don't give up! this is a fantastic project!
There is a way to give you more detailed log? I'm not a pro in android but I'll be glade to help you out with this project

**Comment by scubajeff** [comment]
you don't need to create the home folder lespas/, it will be created by lespas app automatically once you signed in. so this makes me wonder where are you guys looking for your files.

lespas/ folder will be created by lespas app in your Nextcloud home folder, lespas will sync album it created in the app to a subfolder with album's name under lespas/. or you can created a subfolder or symlink a traget as a subfolder under lespas/ on the server side, lespas app will sync them to your phone as an album, of course empty folder will not show up, since lespas organize photos into album and needs at lease one photo to act as the cover art. recursion folders are fine and will not stop lespas from syncing, just that it won't walk further down any subfolders in the album's folder.

the other possibility will be WebDAV, it's related to sever setup of Apache or/and PHP that stop WebDAV from reading symlink files. That's something not easy for me to debug remotely. However, I didn't make any special configuration when I setup my own Nextcloud server and I tested symlinked folder,  works for me here.

**Comment by scubajeff** [comment]
So could you guys please elaborate a little bit more about how you put files into lespas/ folder? Thought it's should be a straight forward thing but devil is in the detail. Many thanks for supporting this project.

**Comment by zoenglinghou** [comment]
ok, so here is my `/lespas` folder:

```
$ ls -l
total 0
lrwxrwxrwx 1 www-data www-data 16 Dec 26 12:14 Movies -> ../Movies/Camera
lrwxrwxrwx 1 www-data www-data 16 Dec 26 12:13 Photos -> ../Photos/Camera
```

and inside these folders are the photos uploaded to NC using the NC App, organized by dates:

```
tree -L 3 -l
.
├── Movies -> ../Movies/Camera
│   ├── 2020
│       ├── 01
│       ├── 05
│       ├── 06
│       ├── 07
│       ├── 08
│       ├── 10
│       ├── 11
│       └── 12
└── Photos -> ../Photos/Camera
    ├── 2020
    │   ├── 01
    │   ├── 02
    │   ├── 03
    │   ├── 04
    │   ├── 05
    │   ├── 06
    │   ├── 07
    │   ├── 08
    │   ├── 09
    │   ├── 10
    │   ├── 11
    │   └── 12
    └── Camera -> ../Movies/Camera
```

For whatever reason, the photos and videos are not showing up. Not sure it is because of the subfolders...

And once again, thank you for building this app!

**Comment by PietroMB** [comment]
At first I didn't create the folder, I waited for the app to do it automatically, but since it didn't, I thought I'd "help" by creating it manually.
I use the standard docker version of nextcloud

Down below the video of what I do after reinstall the app via f-droid

https://user-images.githubusercontent.com/15186555/103150619-38d30a80-4776-11eb-8d96-95312071a8c6.mp4

**Comment by PietroMB** [comment]
I realized now that a strange thing happens, the application does not use the internet at all
![photo_2020-12-26_12-33-55](https://user-images.githubusercontent.com/15186555/103150679-a2531900-4776-11eb-8b6f-d9244da35b48.jpg)

**Comment by scubajeff** [comment]
i see. lespas only sync files in the subfolder and the subfolder only, won't walk down further. so in your case, files in Movies and Photos should be synced to your phone, but those in 2020 and 01, 02, etc. won't. seems like lespas's  folder structure is not what you like. ;)

**Comment by scubajeff** [comment]
@PietroMB if it singed in and created the folder, then the app should have use the network. 

lespas default setting is to Not use mobile network.

**Comment by ohthehugemanatee** [comment]
Having this trouble, too. The app created `/lespas`, and I've tried

* copying some image files directly into `/lespas`. They do not appear in the app.
* symlinking my `/Camera Uploads` directory to `/lespas/Camera Uploads` with `cd lespas && ln -sf ../Camera\ Uploads`. This directory contains photos uploaded from my phone. This does not appear in the app.
* symlinking my `/archive/Photos` directory to `/lespas/archive`. This contains a subdirectory per year with all photos from that year. I understand these should not sync, but they won't break anything either. This does not appear in the app.
* Create a new album called `test album` in the app with one photo, and see that it uploaded correctly (it did).

It certainly looks like there's no problem with WebDAV: the local client (which uses WebDAV I believe) wants to sync the entire lespas directory.

Replication isn't hard: just validate against publicly available docker images of nextcloud. I'm using [linuxserver/nextcloud](https://github.com/orgs/linuxserver/packages/container/package/nextcloud), so you can try with that. It builds off of alpine with NGINX. So maybe the issue is with NGINX?

**Comment by scubajeff** [comment]
@ohthehugemanatee those are exactly as designed. Albums in app have one to one relationship with a subfolder under lespas/ on server, e.g., album "Trip to Paris" in app will sync to server as a subfolder named "Trip to Paris", all the photos in that album will reside in that folder too. Of course you can create that subfolder on server first and then sync to app on phone side. Any file in lespas/ folder or any subfolder within subfolder will be ignored. 

This is what Les Pas is designed for, a photo management app based on Albums.

**Comment by ohthehugemanatee** [comment]
I tried creating a directory and adding a handful of photos to it... that worked as expected (was visible as a gallery in le pas). So it seems like - at least in my case - if le pas finds _any_ subdirectories, it ignores the whole directory. @scubajeff is this the intended behavior?

I suggest a more intuitive behavior is either:

* ignore subdirectories, and build an album from just the top level directory and its photos, OR
* traverse the directory structure and build an album from each directory with its photos, regardless of where it sits in the hierarchy.
  * you'd have duplicate naming trouble here, for example `2020/favorites` and `2019/favorites` would produce duplicate names. But that's easy enough to solve with a naming structure that includes the full hierarchy.

Is there interest in a patch for one or the other behavior? I've never written in Kotlin, but these behaviors strike me as pretty beginner-friendly...

**Comment by scubajeff** [comment]
@ohthehugemanatee Ever since I released this app, I have received so many different kinds of requests on how photos should be organized, by years, by tags, by location, by faces, etc. Each and every one of them has it's solid point. But I believe by event is the most simple and effective way. Because when someone starts searching his/her memory for a moment in the past, it's hard to recall exactly when or the exact location or people around, however it would be easy to remember what exactly happened during that period of time, like it's my little boy's birthday, or it's a family trip to Maldive. Organize photos by events or I should say in Album in our case here, requires extra effort, you just can't rely on machine to sort it out for you. But in the long run, it is the best way to find your photos.

**Comment by ohthehugemanatee** [comment]
TBH i personally just like all my photos in there chronologically. But i hear you, everyone has their way of organizing.

IMO there are two separate technical issues here: how to get photos to sync, and how to organize the display of synced photos.

I suggest:

* sync every image under `/lespas` (or whatever, see #3 ), regardless of directory structure. Save yourself the trouble of supporting all us weirdos with our edge cases. :) 
* have the app keep metadata tags for each image, and allow the user to choose a metadata tag source for their grouping. So you could group by:
  * path based tags
  * nextcloud's own tags (that covers "events")
  * file date component (eg "year")
  * anything any other Nextcloud App stores on a file. For example, the face recognition app stores the names of faces it has identified in each picture, and the app would automatically allow me to group that way.

This makes for maximum flexibility and integration with everything else in the Nextcloud ecosystem. The only problem is, I'm not sure if the Nextcloud API lets you query for metadata in such an open-ended way.

**Comment by scubajeff** [comment]
This is exactly what I did about 15 years ago. Gallery program in Windows first introduced this feature, I was so fond of it and tagged almost every single one of my photos with it. But then, I decided Linux is the way to go and those tags and the time I spent on them are all wasted. Since then, I made up my mind not to rely on any specific features of a platform. Nextcloud is good and I'm a happy user of it right now, but who knows what will happen 2 years down the road.

**Comment by ohthehugemanatee** [comment]
ok, so how do you see handling "events" using only native filesystem and EXIF attributes?

**Comment by scubajeff** [comment]
I think I have made my point clearly, I will only use platform independant ways to manage my collection. Just try to balance between portability and fuctionality.

**Comment by ohthehugemanatee** [comment]
Yes, I understand your point and you did make it clearly. I'm asking about how you plan to implement so I can offer help and/or realign how I organize my photos to try and match. Apologies if the text isn't carrying my intended, constructive tone.

**Comment by scubajeff** [comment]
I don't really have a thoughtful plan right now, maybe a search function.
