### ISSUE TITLE
choose what folder you want to sync to the phone

### ISSUE THREAD

**Issue by polypom** [scubajeff/lespas#22]
Hi, first of all thank you for the great app! It is already super useful.

However it would be nice if there is the feature to exclude some folders being downloaded to the smartphone. Couldn't be there a possibility to just preview them in the app and downloading them temporarily if clicked?

Would be useful to save space. Right now your Le Pas Gallery is limited to the storage size of your phone.

**Comment by scubajeff** [comment]
@polypom that's a request of totally different feature. Latest release support viewing friend's publication with the help of okhttp cache and evoplayer's streaming support, so it's not hard applying these onto user's own album too. Just need to sort out user experience design.

**Comment by polypom** [comment]
Sounds good! Anyways thank you for the work

**Comment by thve25** [comment]
Hi, Thanks for the great app! I'm using it as my default photo archive nowadays,  instead of google photos.

I would really like to have the option to disable a folder to be synced, while still being able to view the album (with thumbnails and download the image when clicked).

Currently, i have to move "finished" albums out of the lespas folder on nextcloud to save space on my phone.

is there any progression on this feature request?

Thanks

**Comment by scubajeff** [comment]
Got to admit that I spent a lot of time on adding new features recently. Will work on this ASAP.

**Comment by scubajeff** [comment]
since this would introduce a new flag indicating remote album, will wait till DB migration finished

**Comment by scubajeff** [comment]
managed to find a way cracking this one, will be released in version 2.5.0

**Comment by scubajeff** [comment]
Eventually this has to be postponed until DB migration complete. In current implemetation, some critical meta info, like GPS location, are extracted from EXIF at-hoc, with media file sitting on server only, things will get messy.
