### ISSUE TITLE
Feature request: Allow changing/cropping album banner

### ISSUE THREAD

**Issue by fcwoknhenuxdfiyv** [scubajeff/lespas#24]
**Is your feature request related to a problem? Please describe.**
It would be nice to be able to change the banner used on an album. I have an album which has cropped the head off for the banner. Not great!

**Describe the solution you'd like**
Allow to choose another photo for the banner at a later time. Also, it would be nice to be able to crop/zoom so that the relevant part is shown i.e. the face of an album for a person.

**Describe alternatives you've considered**

**Additional context**

**Comment by scubajeff** [comment]
Ever since the first release, Les Pas has this function to choose any photo as it's album cover. Latest release support setting video item as album cover too. However, due to this function is not a frequestly used one, it's buried deep in the menu. 

Go to the album's photo list, click on the one you would like to set as cover, Les Pas will use full screen to display this photo, touch the screen, a menu will show up at the bottom of the screen, click on the More button on the far right, another row of function buttons will reveal themselves now, the very left one of it is the Cover Setting. In the cover setting screen, you can move the cutting frame up & down, zooming is not implemented yet.

**Comment by fcwoknhenuxdfiyv** [comment]
Wonderful!
