### ISSUE TITLE
lost images when creating album with "move" function

### ISSUE THREAD

**Issue by hktari** [scubajeff/lespas#56]
**Describe the bug**
Create a new album and select multiple pictures. Also select the "move"function.  The pictures aren't uploaded to the cloud and I've not found any way to access the pictures on my phone disk after removing the app.

Very disappointing.

Using on Pixel 2, got version from droid-f in the last month

**Comment by scubajeff** [comment]
Sorry that this app didn't work out for you.

"Move" means removing the source after the file transfer, that's what it does. As for uploading, there is a setting in app's Preference screen "Sync only on Wifi", and that setting is default to on. If you are sure you were on WiFi when all these were happening, that sure is a syncing bug. But I'm afraid we can't do much at the moment since you've already removed the app.

**Comment by hktari** [comment]
that sucks.

I like the UX a lot, but syncing just didn't work for me. I'm pretty sure I
turned off snyc only on wifi.

Am Mi., 4. Mai 2022 um 03:41 Uhr schrieb scubajeff ***@***.***

**Comment by scubajeff** [comment]
Since you have already uninstalled the app, there is nothing more I can help here

**Comment by scubajeff** [comment]
Could be releted to a bug introduced by release 2.5.6 which accidentally turn off the background auto sync setting. Release 2.5.9 fixed this.
