### ISSUE TITLE
No sync with active VPN connection

### ISSUE THREAD

**Issue by danielb42** [scubajeff/lespas#68]
Les Pas v2.5.10 doesn't sync when a vpn connection is active. When I disable the VPN connection, sync happens immediately. Unfortunately I cannot disable this connection outside of my current testing setup as it's necessary to reach my "productive" Nextcloud.

VPN is tinc with https://github.com/pacien/tincapp

**Comment by scubajeff** [comment]
i'll look into this.

**Comment by danielb42** [comment]
Great, thanks

**Comment by danielb42** [comment]
Just stumbled upon how other apps solve this issue - by providing separate options "Only do stuff over wifi" and "Only do stuff over unmetered wifi". Could you handle it like this as well? This way, vpn-users could leave the second option unchecked, while someone who wants to avoid *actually metered* WiFis would check both.

**Comment by scubajeff** [comment]
VPN service is considered metered by default. It's up to the service app's job to set it not if that's the case. I had a quick look at other VPN app's code, like Shadowsocks, OpenVPN, AdguardVPN. They all handle this properly. The key is calling android's API `setUnderlyingNetworks`. I can't find any of it in Tinc's code. So I believe this issue should be raised to Tinc's team.

As for why Nextcloud didn't stop syncing, turns out it simply ignores NET_CAPABILITY_NOT_METERED flag, resorts to NET_CAPABILITY_NOT_RESTRICTED flag instread. I don't believe that's a good practice.

**Comment by danielb42** [comment]
> VPN service is considered metered by default. It's up to the service app's job to set it not if that's the case. I had a quick look at other VPN app's code, like Shadowsocks, OpenVPN, AdguardVPN. They all handle this properly. The key is calling android's API setUnderlyingNetworks. I can't find any of it in Tinc's code. So I believe this issue should be raised to Tinc's team.

Thanks, I'll raise an issue with them.

> As for why Nextcloud didn't stop syncing, turns out it simply ignores NET_CAPABILITY_NOT_METERED flag, resorts to NET_CAPABILITY_NOT_RESTRICTED flag instread. I don't believe that's a good practice.

Interesting. But I guess if the official client would be all good practice and feature, then there would be no need for things like Les Pas. ;)
