### ISSUE TITLE
App crashes on tapping "Kamerarolle" 

### ISSUE THREAD

**Issue by tgaertner** [scubajeff/lespas#9]
**Describe the bug**
App crashes on tapping "Kamerarolle". I'm not sure what is should do, its my first use of the App. Also the wording " Kamerarolle" is not clear to me and seems to me like a wired translation...

**Smartphone (please complete the following information):**
 - Device: Motorola Moto G7
 - OS: Android 10 (LineageOS)
 - lespas 1.4.4 from F-Droid

**Comment by scubajeff** [comment]
For the sake of privacy, I don't collect log in this app. So there is no easy way to debug. I would suggest installing lespas onto another phone and see if it works there. Then we could narrow down the cause.

As for the translation, I use DeepL. It's Camera Roll in english. Appreciate if you can suggest a better german name for it.

**Comment by tgaertner** [comment]
Well the "right" German word would be "Filmrolle" BUT still don't get by this translation what this mean or what will happen if I click on it...

Installed on an "BQ Aquaris X" LineageOS and it works there, though it shows me just a message "No media found in camera roll" (free translated).

Both devices have LineageOS 17.1 Android 10.

**Comment by scubajeff** [comment]
This function is to manage photos/videos captured by your phone, "Gallery" might be a more appropriate name for it but since LesPas is a gallery app by itself, I borrow "Camera Roll" from iOS instead.

If there is no photos/video in your phone's DCIM folder, LesPas will prompt you with this message: "No media found in camera roll". If there are some photos/video file in your phone, LesPas will use Android standard MediaStore API to get information of them. I suspect that the crash might happen there due to some differences between AOSP and Lineage.

So could you please help me out by taking some photos with your BQ Aquaris X, then tap "Kamerarolle" to see if it also crashes?

**Comment by tgaertner** [comment]
So "Camera Folder" would give me a gold idea what that item is for imho.

Anyway. In Aquaris X clicking on "Camera Roll" shows me the taken pictures. So its working. 

Still don't get how the sync work since these pictures are not synced to nextcloud ( bit I see some folders created funnily by the Motorola) but that's an other topic that should not be covered in this ticket.

So what else can I do to help find the error?

**Comment by scubajeff** [comment]
The albums you created will be synced to Nextcloud under /lespas folder, this is done automatically.

But you need to turn on "Camera Roll backup" in the setting to enable backup "camera folder" to Nextcloud under /DCIM folder. Please note that it's one-way backup only, not sync.

Do you have any photo taken in the Motorola? If you do, I bet you also have a file app installed, you can try to click open a photo in your file app, since now you have Lespas installed, Android will prompt you to choose an app to view the photo, select Lespas and see if Lespas can successfully view these photos. Since viewing photo and managing camera roll functions are in the same activity, I can further narrow down the cause. Please try this on a couple of different photos, the lastest one, the earliest one, and shoot some new ones.

**Comment by tgaertner** [comment]
Mh that worked - opened the photo directly and it showed up in lespas. SInce then I can even open the "Camera Roll" from lespas directly, BUT its crashing again when I switch photos to view...

So the only thing that is synced are the galleries - right? If the "Camera Roll" just uploads the Photos one way there is no benefit in that function for me because nextcloud app can do the same but much more flexible (like choosing remote and local location).

I thought, and what would be my usecase, is to sync (both ways) my photos taken by the camera (by the way that have not to be always DCIM folder - for there are cam apps where I can choose the storage location) without moving them somewhere or adding them to a gallery. Basically a replacement for Google Photos. Is this somehow achievable by lespas?

**Comment by scubajeff** [comment]
if i understand correctly, there seems to be a specific photo which will crash the app. maybe a high resolution photo. did you install lespas from f-droid or google play? the latest version on google play is 1.4.5 which will fix this issue.

camera roll is one way backup. i thought about the "adding more backup folders" function you suggest, it's not difficult to implement. but since google is tighten up privacy in latest version of android. it will be difficult to access files created by other apps in the near future. the only fesible way is to go through standard Mediastore API. i decided to wait and see how quickly google is rolling out these security/privacy features.

**Comment by scubajeff** [comment]
version 1.4.5 is lived on f-droid now, please update to this version and see if it fixes the crash. many thanks.

**Comment by tgaertner** [comment]
New version does not solve the problem. I can help solve the problem, but honestly I stopped using the app for now because it does not fit to my usecase.

**Comment by scubajeff** [comment]
thank you for your help.
