### ISSUE TITLE
Java.lang.NullPointerException in OkHttpWebDav.kt prevents synchronization

### ISSUE THREAD

**Issue by DeveloperOl** [scubajeff/lespas#96]
**Describe the bug**
This bug occured to me the second time now, so I decided to investigate. The synchronization got stuck at video files sometimes without a clear indication why and when.
I can not find a 100% way to reproduce, but when this bug occures, no more synchronization will be done by lespas at all.
Maybe the linked PR can give you a hint if there is a better way to fix it.

**To Reproduce**
1. Somehow get the NullPointer Exception.
2. Get sad when you realize no more synchronization occures.

**Expected behavior**
Synchronization should reset completely if a file upload fails.

**Smartphone (please complete the following information):**
I'll leave this blank, as it's probably unrelated.

**Additional context**
I attached a PR.
The problem seemed to be the variable "this.filename" resolved to ".file". 
This resulted in this.name.substringBefore('.') to be an empty string, further resulting in a NullPointerException when calling the .toLong() function.
It may be a dirty fix, so I leave it open to you, if you accept the PR or just make a better change yourself.

**Comment by scubajeff** [comment]
Thanks for reporting this. This must be an edge case when Nextcloud server generates files with unexpected filename in chunk upload folder.

PR is not accepted because there is another irrelevant merge commit in it. I have made my own fix.

Skipping file in trouble of uploading is planned, but need to sort out UX design on how to report those cases to user.

**Comment by DeveloperOl** [comment]
I updated the PR and removed the merge commit.
